### PR TITLE
Build RHEL 8 on RHEL 8 builders

### PR DESCRIPTION
**Pull request by tas50**
This resolves some Qualys scan failures related to FedRAMP

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3727

**Comment by tas50** [comment]
Blocked on perl failing to compile

**Comment by ramereth** [comment]
> Blocked on perl failing to compile

I seem to recall running into this a long time ago with Cinc. I may have opened an old PR in omnibus-software at some point or an issue?

**Comment by tas50** [comment]
We have the new Perl release in omnibus-software now. We just need to test it together with sqitch to make sure we don't break any functionality. We're going from a 2013 Perl to a 2019 Perl so there's a high chance that something breaks.

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3906

**Comment by tas50** [comment]
Closing this out since it's not working and we have the blocker identified.

**Pull request closed without merging**
