### PR TITLE
Bifrost & Mover build on Olde CI

### PR DESCRIPTION
**Pull request by joedevivo**

### CODE REVIEW

**Comment by stevendanna** [comment]
:+1:

**Comment by marcparadise** [comment]
The change looks good, but also take the lines from erchef's build.sh to upload packages for both ubuntu-10.04 and ubuntu-12.04, instead of using the source machine type. You can then delete lines 10,11,12

**Comment by marcparadise** [comment]
Extra note: use caution - when I copy-pasta'd that from erchef to mover, I got tripped up because the deploy of mover used underscores in the file name, while I had used hyphens.  I changed the cookbook in that case, because +1 to consistency...

**Comment by sdelano** [comment]
It seems odd to me that we have to hard-code the version number into this. Is there something we can do consistently across these projects to dynamically generate the release version number?

**Comment by marcparadise** [comment]
Not the version number, just 'ubuntu-10.04' and 'ubuntu-12.04'

**Comment by sdelano** [comment]
:+1:

**Pull request merged**
