### PR TITLE
fix oc_id recipe so that it doesn't try to parse log messages as json

### PR DESCRIPTION
**Pull request by sdelano**
Since we changed the #command method enough, I decided that it was
best to remove it and inline it into the calling function so that
nobody else tries to use it. This was the only place where that
function was called to begin with.

/cc @chef/lob @schisamo @PrajaktaPurohit

### CODE REVIEW

**Comment by sdelano** [comment]
also /cc @smith @mmzyk

**Comment by stevendanna** [comment]
:+1: for a pragmatic solution

**Comment by schisamo** [comment]
:+1:

**Comment by marcparadise** [comment]
:+1:

**Pull request merged**
