### PR TITLE
Split keys_spec.rb into user_, client_keys_spec.rb

### PR DESCRIPTION
**Pull request by jrunning**
Supports work to bring chef-zero closer to parity with chef-server. See chef/chef-zero#199.

### CODE REVIEW

**Comment by danielsdeleo** [comment]
:+1: For some background, user multi-key is troublesome in some modes of Chef Zero operation that don't support multi-org (like when using ChefFS). The way the tests were organized before, you could skip the actual tests by tagging them appropriately, but many of the `before` blocks would still run tasks relevant just to users.

**Comment by tylercloke** [comment]
Running it through wilson http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/53/downstreambuildview/

**Comment by jrunning** [comment]
Fixed issues with erchef (hopefully), running a new job on Wilson now: http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/54/downstreambuildview/

**Comment by tylercloke** [comment]
:+1: Looks reasonable.

**Pull request merged**
