### PR TITLE
License Enforcement Application

### PR DESCRIPTION
**Pull request by jashaik**
### Description

[Please describe what this change achieves]
License Enforcement Application
### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by jashaik** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6754

**Comment by talktovikas** [comment]
Verify is green: https://buildkite.com/chef/chef-chef-server-main-verify/builds/11062#01932a0a-a36a-4a94-b6d7-968b5a98d682

**Comment by talktovikas** [comment]
Adhoc for this: https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6802

**Review by talktovikas — APPROVED** [review]

**Comment by jashaik** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6802

**Comment by jashaik** [comment]
https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/2546#_

**Pull request merged**
