### PR TITLE
Remove Oliver Ferrigni

### PR DESCRIPTION
**Pull request by oferrigni**
Unfortunately, I don't have the bandwidth to honor this commitment. Grateful for the time I was associated with this project.

### CODE REVIEW

**Comment by oferrigni** [comment]
Feel free to redo from a DCO signed-off committer.

**Comment by adamhjk** [comment]
gif-keyboard-8853778404206104934

**Comment by stevendanna** [comment]
❤️ ❤️ ❤️ Thanks for all of your contributions to Chef!

**Comment by marcparadise** [comment]
👎 You can never truly leave!

**Comment by tylercloke** [comment]
<3

**Comment by stevendanna** [comment]
This was done in d56b86d0d91dba13caa66778d43787e6d9ffeb85.

**Pull request closed without merging**
