### PR TITLE
Repair incorrect DTD

### PR DESCRIPTION
**Pull request by juliandunn**
This has always bothered me!

### CODE REVIEW

**Comment by stevendanna** [comment]
:+1: but...can we go further?  Do we need these?  Why would the core API ever return HTML errors? Seems like we should return JSON errors.

**Comment by smith** [comment]
@juliandunn why not just make it HTML 5 with `<!DOCTYPE html>`?

@stevendanna from here it looks like only 404 and index.html are used: https://github.com/chef/chef-server/blob/ad878ecf61c1e40171f7499a946e649a2d4e6629/omnibus/files/private-chef-cookbooks/private-chef/templates/default/nginx/nginx_chef_api_lb.conf.erb#L29-L34

**Comment by juliandunn** [comment]
@smith I could certainly do that... if we're sticking with HTML for the error pages.
@stevendanna I can definitely just convert these to JSON errors if you can give me an idea of what should correctly go in that payload?

**Comment by smith** [comment]
I think we already have JSON versions: https://github.com/chef/chef-server/blob/ad878ecf61c1e40171f7499a946e649a2d4e6629/omnibus/files/private-chef-cookbooks/private-chef/files/default/html/409.json, et al.

index.html and 404.html should stay for when somebody's requesting pages from a browser and doesn't have Manage installed.

**Comment by stevendanna** [comment]
So, it seems like:

- [] remove all but index.html and 404.html
- [] fix index.html and 404.html using `<!DOCTYPE html>` is the todo

I think serving a 404.json when the content-type requested is application/json can be done separately as it will likely take some nginx config changes.

**Comment by juliandunn** [comment]
There's also `503.json` that I need to leave behind because of this:

`    error_page 503 =503 /503.json;`

**Comment by smith** [comment]
:+1: on this; it looks like we keep the same behavior but delete a bunch of stuff which is the best.

The right thing might be to serve html or json depending on the accept header and have a 404/503/json/html. This gist shows an example of how that might be done: https://gist.github.com/lextoumbourou/d6221deb818da4f342ea

**Comment by stevendanna** [comment]
:+1:

**Pull request merged**
