### PR TITLE
Adding configurability for erchef and bifrost logging messages per second

### PR DESCRIPTION
**Pull request by shruthi-venkateswaran**

### CODE REVIEW

**Comment by stevendanna** [comment]
:+1: Thanks!

**Comment by marcparadise** [comment]
:+1: and thanks

**Comment by bdangit** [comment]
:+1: another on the books

**Comment by irvingpop** [comment]
:+1:

**Comment by stevendanna** [comment]
d'oh, forgot the changelog entry. That is my fault.

**Comment by shruthi-venkateswaran** [comment]
Oh sorry I missed about that. It's clearly mentioned in the README. Will keep in mind for next time :)

**Pull request merged**
