### PR TITLE
Add user_keys, client_keys tags in oc-chef-pedant keys_spec.rb

### PR DESCRIPTION
**Pull request by jrunning**
These changes support work in progress to bring chef-zero closer to parity with chef-server in chef/chef-zero#193 and chef/chef-zero#196.

- Add `:user_keys` and `:client_keys` tags
- Add some missing `:authentication` and `:authorization` tags
- Fix issue with username collision (`Time.now.to_i` was used to generate username suffixes, causing two users that were meant to be distinct to have the same name).

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @jrunning

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by stevendanna** [comment]
:+1: This looks reasonable.  We'll merge after the next release.

**Comment by danielsdeleo** [comment]
:+1: @chef/chef-server-maintainers 12.4 is out so this is good to go, yeah?

**Comment by sdelano** [comment]
:+1:

**Comment by marcparadise** [comment]
:+1:

**Comment by marcparadise** [comment]
Oops - I think it needs a rebase though.

**Pull request merged**
