### PR TITLE
Update runit cookbook to a current version

### PR DESCRIPTION
**Pull request by marcparadise**
Signed-off-by: Marc Paradise <marc@chef.io>

### CODE REVIEW

**Comment by stevendanna** [comment]
We should definitely run this through wilson before merging.  The runit cookbook has had a TON of changes between those versions I think.

**Comment by marcparadise** [comment]
In exciting news, our first wilson run has already failed! (Licensing)

**Comment by tas50** [comment]
1.6 -> 1.7 was a complete rewrite of the LWRP. After that it's mostly just deprecating support for old platforms.

**Comment by marcparadise** [comment]
superceded by https://github.com/chef/chef-server/pull/1200

**Pull request closed without merging**
