### PR TITLE
Upgrade PostgreSQL to 9.2.14.

### PR DESCRIPTION
**Pull request by rhass**
This upgrades PostgreSQL to the current release and addreses several
CVEs.

http://www.postgresql.org/docs/9.2/static/release-9-2-11.html
http://www.postgresql.org/docs/9.2/static/release-9-2-14.html

### CODE REVIEW

**Comment by rhass** [comment]
I am not really sure what to do about this failed unit test. This looks like a bug in the test to me:
```
=INFO REPORT==== 8-Oct-2015::19:52:27 ===
starting stats_hero_sender_sup with 5 senders
depsolver_tests: event_logging_test_ (event logs are captured)...*failed*
in function depsolver_tests:'-event_logging_test_/0-fun-2-'/1 (/home/travis/build/chef/chef-server/src/chef-mover/_build/test/lib/depsolver/test/depsolver_tests.erl, line 88)
in call from depsolver_tests:'-event_logging_test_/0-fun-6-'/0 (/home/travis/build/chef/chef-server/src/chef-mover/_build/test/lib/depsolver/test/depsolver_tests.erl, line 88)
**error:{assertEqual_failed,[{module,depsolver_tests},
                     {line,88},
                     {expression,"filelib : wildcard ( \"/tmp/depsolver-test/ok/*\" )"},
                     {expected,["/tmp/depsolver-test/ok/1",
                                "/tmp/depsolver-test/ok/2",
                                "/tmp/depsolver-test/ok/3",
                                "/tmp/depsolver-test/ok/4"]},
                     {value,["/tmp/depsolver-test/ok/1",
                             "/tmp/depsolver-test/ok/2",
                             "/tmp/depsolver-test/ok/3"]}]}
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 986.
===> Error running tests
make: *** [all] Error 1
The command "USE_SYSTEM_GECODE=1 LIBRARY_PATH=$CHEFDK_GECODE_PATH/lib LD_LIBRARY_PATH=$CHEFDK_GECODE_PATH/lib CPLUS_INCLUDE_PATH=$CHEFDK_GECODE_PATH/include make travis" exited with 2.
```

**Comment by stevendanna** [comment]
@rhass Apologies for the hassle of that failed test.  That particular test is a bit flaky and is unlikely to have anything to do with your change.

**Comment by marcparadise** [comment]
@rhass Thanks for this - do you have a signed CLA on file? Usually currybot tells us about these things.

**Comment by rhass** [comment]
@marcparadise I have signed the CLA, and it looks like currybot already added the Signed CLA label to the PR.

**Comment by marcparadise** [comment]
Thanks @rhass - I see it now from five days ago, but oddly it wasn't showing for me earlier. in any case, barring errors against our internal CI pipeline, this should land sometime tomorrow . Thanks again!

**Pull request merged**
