### PR TITLE
Remove duplicate rubygems pin and roll back to 2.7.X

### PR DESCRIPTION
**Pull request by tas50**
This version was being pinned twice. No need for that.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
@markan It looks like we weren't actually running rubygems 3.x then because that code is not 3.x ready. Let me update this to just pin to 2.7.8 and we can get things over to 3.x later.

**Comment by markan** [comment]
This is ready to merge once we fix the failing tests in travis. Don't think its related to this PR but haven't had a chance yet to confirm.

**Comment by markan** [comment]
After rebasing it looks like the only thing left is the pin back to rubygems 2.7.X; I assume we still want to do that, right?

**Comment by tas50** [comment]
I've entirely forgotten why we had to roll back to 2.x.

**Comment by markan** [comment]
I think we don't need this anymore, closing.

**Pull request closed without merging**
