### PR TITLE
[CHEF-6100 CHEF-6112] GTM and OneTrust changes

### PR DESCRIPTION
**Pull request by ayush-billore**
### Description

- Add onetrust
- Add GTM

https://chefio.atlassian.net/browse/CHEF-6100
https://chefio.atlassian.net/browse/CHEF-6112

https://github.com/chef/chef-server/assets/102516633/1d7ba2b6-d472-4e6c-83a0-a59ab871a7ec

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Review by saghoshprogress — APPROVED** [review]

**Review by marcparadise — CHANGES_REQUESTED** [review]
We need to be very careful adding any kind of analytics in this space, and very clear that this is disabled by default and only enabled when configured. 

To help with that the commit message and the PR should include wording to the effect of: 
```
Add support for Google Tag Manager and OneTrust to oc-id.

Both are disabled by default and must be explicitly enabled in server configuration." 
```
Please squash commits and rebase.

**Comment by ayush-billore** [comment]
> We need to be very careful adding any kind of analytics in this space, and very clear that this is disabled by default and only enabled when configured.
> 
> To help with that the commit message and the PR should include wording to the effect of:
> 
> ```
> Add support for Google Tag Manager and OneTrust to oc-id.
> 
> Both are disabled by default and must be explicitly enabled in server configuration." 
> ```
> 
> Please squash commits and rebase.

Thanks mark for the suggestion, this message clearly conveys the intention of the work.
I will make the changes . Thanks!

**Comment by IanMadd** [comment]
What versions of server is this going to be released in? Just the latest version of 15.x?

**Comment by karunesh-tech** [comment]
Hi @jashaik 
Can we please merge this if there is nothing pending on this one. We need to proceed with dev-complete status for GDPR activity, this closure will help us to update other stakeholders for the same.

**Comment by ayush-billore** [comment]
> What versions of server is this going to be released in? Just the latest version of 15.x?

@jashaik @marcparadise @kalroy @karunesh-tech

**Comment by jashaik** [comment]
> What versions of server is this going to be released in? Just the latest version of 15.x?

@IanMadd it will be a patch release of 15.9 chef-server.

**Review by jashaik — APPROVED** [review]

**Comment by IanMadd** [comment]
@ayush-billore See changes in #3757. You can delete the docs changes in this one. I included them in 3757.

**Comment by sreepuramsudheer** [comment]
Adhoc build: https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6064

**Pull request merged**
