### PR TITLE
Add Gemfile.lock for omnibus

### PR DESCRIPTION
**Pull request by tas50**
This way we have repeatable builds. This particular update also brings in the new openssl 1.0.2y

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/2112#dc0e6f42-b797-4950-8e34-cecb9bb01c11

**Comment by PrajaktaPurohit** [comment]
Thank you for taking the time to do this @tas50. While I understand the rationale for the change and dependable builds would be great, I am a little skeptical adding a Gemfile.lock for omnibus unless there is a mechanism to autoupdate the Gemfile.lock on every change to omnibus-software. 
Some of the things I am concerned about:
1. It is difficult to track failures in the pipeline, I worry that adding Gemfile.lock will provide a false sense of security and updating chef-server will start to fall behind.
2. It is often easier to fix the error in the context of the change made.
3. The other issue would be that that would mean master is not shippable.
I am open to discussing this further. As an interim it might be helpful to run a chef-server adhoc build that points to the branch in omnibus-software with changes before a PR in omnibus-software is merged.

**Comment by PrajaktaPurohit** [comment]
I think we can merge this once we add the dependabot to create PR's on merge to omnibus-software. (and after rebase) :)

**Comment by tas50** [comment]
This fixes https://github.com/chef/chef-server/issues/2254

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/2119#7951c31c-8fb0-4487-b229-cf849e8be735

**Comment by tas50** [comment]
Merging this to prevent further changes in omnibus/omnibus-software from coming in while we troubleshoot failures

**Pull request merged**
