### PR TITLE
Grab umask for gather-logs

### PR DESCRIPTION
**Pull request by sean-horn**
Signed-off-by: Sean Horn sean_horn@chef.io

### CODE REVIEW

**Comment by srenatus** [comment]
@sean-horn That's an interesting thing to look at -- was this caused by any specific issue you've seen in the wild? I'm asking because alternatively, we could also explicitly set `umask` where we care for it; and I'm not certain I could say _where that is_.

(Also, could you sign-off your commit? Simply `git commit --amend -s` and force-push this branch.)

**Comment by srenatus** [comment]
Wait, you have signed-off, but in a format the bot doesn't understand.
You've probably got some script in place to add this? Could you ensure it adds this instead?

```
Signed-off-by: Sean Horn <sean_horn@chef.io>
```

**Comment by srenatus** [comment]
Also, nevermind, I've found the conversation in slack (https://chefio.slack.com/archives/C07JP2K7F/p1490221271817062)

**Comment by marcparadise** [comment]
Replaced by #1266 which rebases and corrects the format of the DCO sign-off.

**Pull request closed without merging**
