### PR TITLE
Update to pick up latest omnibus and omnibus software

### PR DESCRIPTION
**Pull request by mmzyk**

### CODE REVIEW

**Comment by stevendanna** [comment]
From the diff it looks like the only bump that affect us is likely openssl.  There is a small config change to pcre.

**Comment by mmzyk** [comment]
Wilson ad-hoc build: http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/159/downstreambuildview/

**Comment by mmzyk** [comment]
@stevendanna Yeah, the intent of this update was to pull in the latest openssl.

**Comment by marcparadise** [comment]
Merging as @mmzyk is out today

**Pull request merged**
