### PR TITLE
Update inet interface

### PR DESCRIPTION
**Pull request by tylercloke**
From @jmink 

[Build](http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/116/downstreambuildview/)

### CODE REVIEW

**Comment by tylercloke** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:  This is part of hardening our erlang services.

**Comment by stevendanna** [comment]
:+1:

**Comment by tylercloke** [comment]
:+1:

**Pull request merged**
