### PR TITLE
Upgrade rails from 4.2.11 to 6.0.3

### PR DESCRIPTION
**Pull request by PrajaktaPurohit**
Update rails to 6.0.3 from 4.2.11.

Antima has tested logging into manage and into supermarket and they are both successful.

Adhoc: https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/1878 - not current.
IntegrationTests: https://buildkite.com/chef/chef-umbrella-master-chef-server/builds/117 - not current.

Current Adhoc build: https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/2464

### CODE REVIEW

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-umbrella-master-chef-server/builds/198#fee790d5-b653-42c0-85c9-350752957781

**Comment by haidangwa** [comment]
@tas50 do we have any timeline when this PR will be approved? I noticed that there is a merge conflict, and I think that needs an update from @PrajaktaPurohit right? We're very interested in getting this PR accepted. Thanks!

**Comment by tas50** [comment]
@haidangwa We're currently looking into a failure in the pipeline with this change. We have a 14.1 release scheduled for next week that includes JRE updates, new status endpoint functionality, a fix for depends in metadata, and mtls support. This change will most likely ship in the next release (14.2) when we get the branch green again. We're trying to ship as soon as we have functionality in a good state vs. holding a large number of changes for bigger releases. Expect more frequent releases as we work on updating rail, postgresql, elasticsearch, and probably java a billion times.

**Comment by btm** [comment]
@meet58 @PrajaktaPurohit This needs a rebase, is that done in another PR?

**Comment by tas50** [comment]
Updating to 6.0.3.6 will probably fix the current pipeline failure

**Comment by snehaldwivedi** [comment]
I have tried all ways I can to replicate it or to understand the reason behind failure but could not replicate it @PrajaktaPurohit  can you please try on your end as you were able to replicate it serval times. I have checked the response local & on buildkite, gone through sign_in code, and its test didn't find anything that can cause such an issue. Also on my end, I haven't seen this issue locally even once. please let me know if you require any other details.

**Comment by PrajaktaPurohit** [comment]
Closing in favor of: https://github.com/chef/chef-server/pull/2535

**Pull request closed without merging**
