### PR TITLE
Fix Infra Server 13 builds

### PR DESCRIPTION
**Pull request by skeshari12**
### Description

Downgraded veil gem version to 0.3.0 

### Issues Resolved

Build is now successfully created and tested to all the listed environment

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by stevendanna** [comment]
@skeshari12 Thanks! Can you explain a bit more about why this downgrade is needed?

**Comment by skeshari12** [comment]
The build was looking for veil version 0.3.0 but due to version 0.3.3 it was failing earlier. I have made the changes and ran the build and it is green now - https://buildkite.com/chef/chef-chef-server-chef-server-13-omnibus-adhoc/builds/70

Earlier failure error : "

Could not find 'veil' (= 0.3.0) - did find: [veil-0.3.3] (Gem::MissingSpecVersionError)
--"

**Comment by stevendanna** [comment]
@skeshari12 Taking a look at buildkite, the only builds I see failing with this issue are on the chef-sever-13 branches, which we aren't using yet.

Once we start working on those branches, we'll want to make any changes related to them against the chef-server-13 branch.

**Comment by skeshari12** [comment]
@stevendanna the PR is raised against https://buildkite.com/chef/chef-chef-server-chef-server-13-omnibus-release build failure and for chef-server-13 branch.

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-chef-server-chef-server-13-omnibus-release/builds/6 is the release pipeline that we expect will be triggered after merging a change to chef-server-13 branch
So, looking at the error at https://buildkite.com/chef/chef-chef-server-chef-server-13-omnibus-adhoc/builds (assuming this is the one to be fixed)
Looks like the Gemfile.locks in the chef-server-13 branch are pinned to 0.3.0 tag of veil in the chef_secrets repo which I would have expected to see but for some reason does not exist, although it does exist in the rubygems source.
Keeping that aside for a minute, it might be of help to update the following lockfiles to 0.3.3 instead
```
➜  src git:(chef-server-13) ✗ ack "veil \(0.3.0\)" --ignore-dir=pkg
chef-server-ctl/Gemfile.lock
5:    veil (0.3.0)
oc-id/Gemfile.lock
16:    veil (0.3.0)
opscode-expander/Gemfile.lock
5:    veil (0.3.0)
oc_bifrost/oc-bifrost-pedant/Gemfile.lock
5:    veil (0.3.0)
```
Unless there is a specific reason to not do that.
This branch has been rebased with current (14.x) master, which is what bring is all the other commits that might not be needed.
You will need to create your branch off of chef-server-13 and apply your changes and then rebase with chef-server-13 if needed and push to chef-server-13.

I had a change running here, but it seems to be blocked by a different error currently.

https://github.com/chef/chef-server/commit/599d24dd4c149cdaa7567fdce1d2fd4a1f254076 is the commit on master that once we decide to bring over the master branch here should fix this issue that you are seeing.

**Comment by skeshari12** [comment]
Not needed anymore, will create new PR

**Pull request closed without merging**
