### PR TITLE
Use NGINX cert path attributes to configure RabbitMQ

### PR DESCRIPTION
**Pull request by schisamo**
These attributes work resolve correctly for a generated SSL cert OR a
full SSL cert path passed in via config.

Signed-off-by: Seth Chisamore <schisamo@chef.io>

### CODE REVIEW

**Comment by schisamo** [comment]
We found this bug when deploying our new internal Chef Server acceptance environment in which we configure the path to an SSL cert/key (vs using the generated one).

**Comment by jaym** [comment]
I think https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/nginx.rb#L79-L80 needs to happen before rabbitmq

**Comment by jaym** [comment]
this does indeed break things. Here's `rabbitmq.config`:
```erlang
root@vagrant:/var/opt/opscode/rabbitmq/etc# cat rabbitmq.config
[
 {kernel, [{inet_dist_use_interface, {127,0,0,1}}]},
 {ssl, [{versions, ['tlsv1.2','tlsv1.1']}]},
 {rabbit, [{tcp_listeners, [5672]},
               {ssl_options,
                 [{certfile, ""},
                  {keyfile,  ""},
                    {versions, ['tlsv1.2','tlsv1.1']}]}
  ]},
 {rabbitmq_management,
     [{listener, [
               {ip, "127.0.0.1"},
               {port,     15672 },
               {ssl, true }
               % The Rabbit Management Plugin will use the global Rabbit SSL Config
              ]}
  ]}
].
```

**Comment by jaym** [comment]
I think everything will work correctly if you swap https://github.com/chef/chef-server/blob/master/inspec/chef-server-smoke/controls/base.rb#L15-L16

**Comment by schisamo** [comment]
@jaym I moved configuration of `rabbitmq` after `nginx`.

**Comment by jaym** [comment]
👍

**Comment by schisamo** [comment]
Successful Ad-hoc build: http://wilson.ci.chef.co/job/chef-server-trigger-ad_hoc/2/downstreambuildview

**Pull request merged**
