### PR TITLE
The README file in this repo has a bad link - [404:NotFound]

### LINKED ISSUE #2161: The README file in this repo has a bad link - [404:NotFound]
The markup version of the readme that is displayed for the main page in this repo contains the following link:
Status code [404:NotFound] - Link: https://github.com/chef/chef-oss-practices/blob/master/projects/chef-server-infra.md
Should this perhaps be the following instead: https://github.com/chef/chef-oss-practices/blob/master/projects/chef-infra-server.md  ?? I suspect so and my submit a PR for this.

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.
If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

### PR DESCRIPTION
**Pull request by MrCull**
### Description

Fixes bad link

### Issues Resolved

Hopefully resolves #2161

### Check List
 n/a for repo readme(??)

### CODE REVIEW

**Comment by PrajaktaPurohit** [comment]
Sorry we missed that! Thank you for your contribution! Could you please sign the DCO for the pull request so we can merge it in.

**Comment by MrCull** [comment]
Thanks for the pointer on the DCO
I've signed now.

**Comment by PrajaktaPurohit** [comment]
Thank you for your contribution @MrCull! If you could rebase against latest master and squash your commits that would be great, if not I will do that before merging.

**Comment by tas50** [comment]
Closing this one in favor of #2212, which makes the same change and performs some additional readme cleanup. Thanks for pointing this out to us @MrCull

**Pull request closed without merging**
