### PR TITLE
Upgrade Erlang to 24.2

### PR DESCRIPTION
**Pull request by lbakerchef**
Signed-off-by: Lincoln Baker <lbaker@chef.io>

### Description

[Please describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by ramereth** [comment]
Any update on this? I believe this might resolve an issue I have trying to build on Debian 11. I'm running into [this](https://github.com/asdf-vm/asdf-erlang/issues/159#issuecomment-904891889) specifically.

**Comment by lbakerchef** [comment]
> Any update on this? I believe this might resolve an issue I have trying to [build on Debian 11](https://gitlab.com/cinc-project/distribution/server/-/jobs/2396433228#L2208). I'm running into [this](https://github.com/asdf-vm/asdf-erlang/issues/159#issuecomment-904891889) specifically.
We have a successful build.  This is currently failing some runtime tests, thus more work is needed.

**Comment by lbakerchef** [comment]
lbaker/scratch5
adhoc: https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/4698
umbrella: https://buildkite.com/chef/chef-umbrella-main-chef-server-full/builds/217

**Comment by lbakerchef** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/4829

**Review by marcparadise — APPROVED** [review]

**Review by vinay-satish — APPROVED** [review]
LGTM

**Pull request merged**
