### PR TITLE
maintainers: remove Ryan Cragun

### PR DESCRIPTION
**Pull request by ryancragun**
This hasn't been true for a while, lets make it official.

Signed-off-by: Ryan Cragun <me@ryan.ec>

Aha! Link: https://chef.aha.io/features/SH-364

### CODE REVIEW

**Review by srenatus — APPROVED** [review]
Hard truth!

**Comment by srenatus** [comment]
Wait, I'm still in @chef/chef-server-maintainers myself? That'll need to be updated.

**Comment by stevendanna** [comment]
@srenatus Updated

**Comment by stevendanna** [comment]
@ryancragun No worries if not, but if you would like feel free to move yourself to the "Past Maintainers" section.

**Review by markan — APPROVED** [review]

**Review by PrajaktaPurohit — APPROVED** [review]

**Pull request merged**
