### PR TITLE
remove postgres92

### PR DESCRIPTION
**Pull request by tehlers320**
Signed-off-by: Timothy Ehlers <tehlers@expedia.com>

### Description

I've compiled and tested a version of chef that does not include postgres92, i believe this was left here for a transition period in chef12 which has long since past.  Its costing the RPM file about 2mb of storage. I could be wrong but i compiled it and ran test 
and test -all and it passed without postgres92 being here. 

Is this needed when upgrading chef < 12.15.9 to above this version? 

### Issues Resolved

None, its just confusing to have postgres92 here if its not used. 

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [X] Full omnibus build and tests in buildkite pass
*i dont know what buildkite is, i built this on the CINC stack. 
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [X] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by tehlers320** [comment]
https://github.com/chef/chef-server/commit/a74d51e1b08c019bc69b74dbd301c4f3710b57da

**Comment by stevendanna** [comment]
@tehlers320 Thanks for the contribution!  You are correct that postgresql 9.2 binaries are required for upgrading from Chef 12.15.9 or earlier.  Next week I'm going to try to clarify with some others what our current minimum upgrade version is.  Our Chef 13 upgrade instructions indicate that the minimum version is 12.17.5 so I _think_ we are OK to merge this but I want to double-check on that first.

**Review by PrajaktaPurohit — APPROVED** [review]
Thank you for the changes! I am creating https://github.com/chef/chef-server/pull/2158 rebased with the latest master and run through the internal build and test pipeline.

**Comment by PrajaktaPurohit** [comment]
Closing in favor of https://github.com/chef/chef-server/pull/2158

**Pull request closed without merging**
