### PR TITLE
Updated rebar3

### PR DESCRIPTION
**Pull request by joedevivo**
also made one make target for omnibus, so if omnibus needs to retry, it
will do so with a distclean as well

### CODE REVIEW

**Comment by marcparadise** [comment]
:+1:

**Comment by marcparadise** [comment]
Kicked off a CI build as well http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/699/downstreambuildview/

**Comment by marcparadise** [comment]
Travis /CT says that it doesn't like a behavior in `the_real_root_dir`, will take a look later today if I can.

**Comment by joedevivo** [comment]
On my local
```
----------------------------------------------------
2015-08-28 10:14:21.946
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build/test/lib/oc_chef_wm/itest/oc_chef_wm_sanboxes_SUITE_data/)


----------------------------------------------------
2015-08-28 10:14:21.946
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build/test/lib/oc_chef_wm/itest)


----------------------------------------------------
2015-08-28 10:14:21.946
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build/test/lib/oc_chef_wm)


----------------------------------------------------
2015-08-28 10:14:21.947
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build/test/lib)


----------------------------------------------------
2015-08-28 10:14:21.947
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build/test)


----------------------------------------------------
2015-08-28 10:14:21.947
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef/_build)


----------------------------------------------------
2015-08-28 10:14:21.947
the_real_root_dir(/Users/joe/dev/opscode/chef-server/src/oc_erchef)
```

**Pull request merged**
