### PR TITLE
Removed foundation-rails gem

### PR DESCRIPTION
**Pull request by antima-gupta**
Signed-off-by: antima-gupta <agupta@msystechnologies.com>

### Description: 
While working on rails version upgrade task, we were facing this issue : https://github.com/chef/chef-server/issues/2047, to resolving the dependency issues, I removed the chef-web-core gem and moved the all the required assets of `chef-web-core` gem  into the `oc-id` assets. In the `chef-web-core` gem assets, it is overriding `foundation-rails` gem JS and CSS, and we are using these override JS and CSS files into the `OC-ID` web pages design. Some CSS files has removed in the `foundation-rails version~> 6` So we can not upgrade it. 

To resolve this I have removed `foundation-rails` gem and added all the required **stylesheets** of **foundation-rails** to `lib/assets/stylesheets/chef/foundation-rails`, so that it wouldn't  throw dependency errors while updating other gems. As `foundation-rails~> 5` gem is dependent on  **railties >= 3.1.0 and sass < 3.5, >= 3.3.0** gems, so basically `saas` gam is used in many parts apart from `foundation-rails`, so if we mute the dependa-bot PR for `saas` that would affect other parts.

Also added `rake assets:precompile` command into the omnibus oc-id software. Removed the unnecessary public assets as `rake assets:precompile` command will add these assets. 

### Issues Resolved

#2623 

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3590

**Comment by antima-gupta** [comment]
Verify Build URL: https://buildkite.com/chef/chef-chef-server-main-verify/builds/5801
Adhoc Build URL: https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3593

**Comment by antima-gupta** [comment]
Updated PR Buildkite URLs:
- https://buildkite.com/chef/chef-chef-server-main-verify/builds/6082
- https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3761

**Comment by marcparadise** [comment]
@antima-gupta this makes sense.  Have you done manual validation as well (checking styles, no new errors loading oc-id pages or using it)?

**Comment by antima-gupta** [comment]
> @antima-gupta this makes sense. Have you done manual validation as well (checking styles, no new errors loading oc-id pages or using it)?

@marcparadise yeah I am doing testing, I informed the same to @PrajaktaPurohit  as well.

**Comment by antima-gupta** [comment]
@marcparadise I have tested these changes on my EC2 instance OC-ID pages looks good.

**Comment by antima-gupta** [comment]
Updated Buildkite-URLs: 
- https://buildkite.com/chef/chef-chef-server-main-verify/builds/6091
- https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3767
- https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/1009

**Comment by PrajaktaPurohit** [comment]
The linked umbrella build does not actually test the changes in this PR, but oc-id has been tested manually after an upgrade and it works as expected.

**Review by PrajaktaPurohit — APPROVED** [review]

**Review by marcparadise — APPROVED** [review]

**Pull request merged**
