### PR TITLE
Add favicons for oc-id and static files.

### PR DESCRIPTION
**Pull request by smith**
Uses the favicon from https://www.chef.io/favicon.ico.

oc-id had a blank file in that place, while the static files did not
have one. Adding the files and the configuration to let nginx serve it.

ChangeLog-Entry: Add a favicon.ico

### CODE REVIEW

**Comment by stevendanna** [comment]
Why do we need the favicon.ico in two places?

**Comment by smith** [comment]
@stevendanna I suppose you're right and we can change the link in the oc-id template. Will change.

**Comment by smith** [comment]
Actually, it will just attempt to load /favicon.ico if you're loading /id/anything so even better.

**Comment by smith** [comment]
@stevendanna updated.

**Comment by stevendanna** [comment]
:+1: here.

**Pull request merged**
