### PR TITLE
Add s390x platform support for z-systems

### PR DESCRIPTION
**Pull request by jaymalasinha**
@chef/engineering-services

### CODE REVIEW

**Comment by scotthain** [comment]
@chef/chef-server-maintainers

**Comment by stevendanna** [comment]
Looks OK to me.  Any particular reason to use `===` over `==` here?

**Comment by scotthain** [comment]
@stevendanna I think that's a typo :D

**Comment by jaymalasinha** [comment]
@stevendanna fixed the "===" please review. Thanks

**Comment by stevendanna** [comment]
👍 mwr

**Comment by yzl** [comment]
👍

**Comment by marcparadise** [comment]
:+1:

**Pull request merged**
