### PR TITLE
Added email host and from address configuration for oc_id

### LINKED ISSUE #547: oc_id: email configuration
I'm setting up an open source Chef 12 server with supermarket, and the password reset service from oc_id fails because the origin host is not set in the production.yml file. Additionally, the from: address is also not overridden.

I've managed to workaround the problem by creating a settings.local.yml file in `/opt/opscode/embedded/service/oc_id/config` containing the following lines:

```
email_from_address: 'Chef Notifications <chef@notchef.io>'
origin: chef.notchef.io
```

But it would be far better to have these lines included in `/var/opt/opscode/oc_id/config/production.yml`

### PR DESCRIPTION
**Pull request by dissonanz**
Fixes #547

### CODE REVIEW

**Comment by tylercloke** [comment]
:+1: Looks reasonable.

**Comment by stevendanna** [comment]
cc @chef/chef-server-maintainers @smith

**Comment by smith** [comment]
:+1:

**Comment by stevendanna** [comment]
@smith Is this still good to merge? It looks like we missed it.  I assume it is fine as this code has changed very little since you reviewed it.

**Comment by smith** [comment]
@stevendanna yes it looks ok to me

**Comment by stevendanna** [comment]
@dissonanz My apologies this was never merged.  Since this was submitted, we've moved from the CLA to "Developer Certificate of Origin".  You can read about the DCO here: https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/

The upshot is, it would be really helpful if you could run:

     git commit – – amend -s

on this branch and then force-push it back up.  Or you can leave a note here saying that you attest to the contents of the DCO and I can add the sign-off for you.

**Comment by dissonanz** [comment]
@stevendanna signed off

**Comment by stevendanna** [comment]
Thanks!

**Pull request merged**
