### PR TITLE
Enable running Chefspec tests against private-chef cookbook

### PR DESCRIPTION
**Pull request by charlesjohnson**
- NEW: Add Chefspec & Berkshelf to Gemfile
- NEW: Add spec/spec_helper.rb for Chefspec
- NEW: Chefspec coverage for recipes/nginx.rb
- FIX: Remove unreferenced servers method from libraries/private_chef.rb (Thanks Mark Paradise)
- FIX: (Minor) clean a few comments in recipes/nginx.rb

### CODE REVIEW

**Comment by charlesjohnson** [comment]
Notes:
- Passes CI
- Adding Berkshelf to the Gemset may be controversial?
- Servers method was blowing up in Chefspec.
- servers method is unnecessary anyway because it conflicted with the servers attribute in the same module, and the attribute always won.

**Comment by marcparadise** [comment]
:+1:

**Comment by charlesjohnson** [comment]
Need berks there so that we can include it during development. If there's a way to have a dev-specific gemset then I'm down to use that.

**Comment by stevendanna** [comment]
I'm not seeing the chefspec coverager for recipes/nginx.rb that is mentioned in the commit message?  Did that get lost?

**Comment by charlesjohnson** [comment]
D'oh! I'll get it into another commit. Thanks.

**Pull request merged**
