### PR TITLE
Update mochiweb to the latest from mochi/mochiweb

### PR DESCRIPTION
**Pull request by irvingpop**
The primary motivation for updating mochiweb is to pull in this fix: https://github.com/mochi/mochiweb/issues/149

In local testing mochiweb appears as version `2.13.0` and passes a full pedant test (`chef-server-ctl test --all`)

### CODE REVIEW

**Comment by irvingpop** [comment]
@stevendanna per your feedback,  I traced the mochiweb dependency:

**Comment by irvingpop** [comment]
One afterthought/question:   Should I update the rebar config and lock for bookshelf and bifrost in this same PR, a different PR, or leave them alone?

**Comment by irvingpop** [comment]
wilson build:  http://wilson.ci.chef.co/job/chef-server-12-build/1509/

**Comment by stevendanna** [comment]
> One afterthought/question: Should I update the rebar config and lock for bookshelf and bifrost in this same PR, a different PR, or leave them alone?

We've been trying to keep core deps like this consistent across projects, so I would definitely be +1.

**Comment by marcparadise** [comment]
This means we're on the wrong webmachine too.  We should be using https://github.com/webmachine/webmachine

**Comment by irvingpop** [comment]
hey @marcparadise @stevendanna since the scope of this PR is creeping bigger and bigger, I propose that we keep the current PR as-is in an effort to be GEFN  (fix the issue that’s affecting customers)  and then work on the `opscoderl_wm` changes in another PR?

**Comment by irvingpop** [comment]
New wilson build containing latest mochiweb for erchef, bifrost and bookshelf:  http://wilson.ci.chef.co/job/chef-server-12-build/1517/

**Comment by irvingpop** [comment]
Update:   Validated the new mochiweb in erchef, bifrost and bookshelf (build 1517) in ec-metal's loadtest environment -  performed as expected.

cc: @sdelano

**Comment by marcparadise** [comment]
Replaced by the changes in #592 , which pull in the new deps via updated https://github.com/chef/opscoderl_wm.

**Pull request closed without merging**
