### PR TITLE
Get back to davisp:jiffy, 0.14.1

### PR DESCRIPTION
**Pull request by joedevivo**
Let's go back to canonical jiffy, so I can delete my fork sometime in this decade :/

### CODE REVIEW

**Comment by tylercloke** [comment]
:+1:

**Comment by marcparadise** [comment]
:+1:

**Comment by stevendanna** [comment]
Do we know why bifrost is so far behind the rest?  :+1: on this, but might be nice to get them all on the same jiffy.

**Comment by joedevivo** [comment]
yeah, I figured the bifrost thing wasn't relevant to the spirit of this pr.

look for some bifrost cleanup soon :D

**Pull request merged**
