### PR TITLE
Remove sentry-raven support in oc-id

### PR DESCRIPTION
**Pull request by tas50**
We're not using this anymore.

Question from the guy that knows nothing about rails: Do we need to move the rails logging setup into another initializer now that the sentry stuff is gone.

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
@saghoshprogress This is probably a good one for your team to review

**Comment by raina4chef** [comment]
Hosted Chef Infra Server does not use this Sentry integration feature.

**Comment by sanga1794** [comment]
PR looks good to me!!

**Review by msys-sgarg — APPROVED** [review]
Looks good to me

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/3828

**Comment by RajeshPaul38** [comment]
Check this file too:
`omnibus/files/server-ctl-cookbooks/infra-server/recipes/oc_id.rb` contains this statement:
```
'sentry_dsn' => node['private_chef']['oc_id']['sentry_dsn'],
```
inside app settings configuration block.

**Comment by RajeshPaul38** [comment]
Should remove mention of sentry from `src/oc-id/CHANGELOG.md`

**Review by RajeshPaul38 — COMMENTED** [review]
Check review comments

**Review by antima-gupta — APPROVED** [review]
Looks good to me.

**Pull request merged**
