### PR TITLE
Don't proxy to local bookshelf if it's disabled.

### PR DESCRIPTION
**Pull request by ameir**
Issue described in https://github.com/chef/chef-server/issues/694.

It's not clear whether `nginx_bookshelf_caching` works for remote bookshelfs; if so, this would need an update to factor that in.

### CODE REVIEW

**Comment by stevendanna** [comment]
Thanks for following up on this!

I don't think nginx_bookshelf_caching works for remote cookbook storage. I suppose it is possible if someone had customized their nginx configuration via the .d configuration directory.  But I think that is an unlikely case and that this is fine.

**Comment by ameir** [comment]
Great; thanks for clarifying.  If there's anything outstanding for this PR, let me know and I'll work on it when I can scrape up some time.

**Comment by stevendanna** [comment]
@ameir The only thing we were thinking of adding was potentially doing *both* this change and tightening up the regular expression.

**Comment by ameir** [comment]
@stevendanna, I updated the regex to what I believe is a safe value.  You may have insights that I don't have, though.  On a default Chef Server install, the `location` block now resolves to:

```
location ~ "^/bookshelf/organization-.+/" {
  proxy_pass http://bookshelf;
}
```

In my tests, things look good.  Let me know what you think.

**Comment by stevendanna** [comment]
gif-keyboard-13008948372314378437

**Pull request merged**
