### PR TITLE
Using keydb for caching dynamic routings

### PR DESCRIPTION
**Pull request by jashaik**
### Description

https://chefio.atlassian.net/browse/CHEF-9582

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All buildkite tests pass
- [ ] Full omnibus build and tests in buildkite pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Review by marcparadise — APPROVED** [review]
I think this looks good, the only concern I have is that the old data will still exist; what will key db do the first time we start it up and data files are already present?

**Comment by jashaik** [comment]
> I think this looks good, the only concern I have is that the old data will still exist; what will key db do the first time we start it up and data files are already present?

⁠
@marcparadise  @kalroy Please find the observation
 - Keydb is trying to load the data from Redis data files as per the logs. It is clear that keydb is not complaining anything about the redis data files infact it is trying to load from the data files. All looks good after loading the redis data files by keydb
```
​2024-08-02_06:20:49.63948 77491:77491:M 02 Aug 2024 06:20:49.639 * monotonic clock: POSIX clock_gettime
2024-08-02_06:20:49.63995 77491:77491:M 02 Aug 2024 06:20:49.639 * Running mode=standalone, port=16379.
2024-08-02_06:20:49.63996 77491:77491:M 02 Aug 2024 06:20:49.639 # Server initialized
2024-08-02_06:20:49.63997 77491:77491:M 02 Aug 2024 06:20:49.639 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
2024-08-02_06:20:49.64044 77491:77491:M 02 Aug 2024 06:20:49.640 * Loading RDB produced by version 6.3.1
2024-08-02_06:20:49.64045 77491:77491:M 02 Aug 2024 06:20:49.640 * RDB age 120 seconds
2024-08-02_06:20:49.64046 77491:77491:M 02 Aug 2024 06:20:49.640 * RDB memory usage when created 1.37 Mb
2024-08-02_06:20:49.64054 77491:77491:M 02 Aug 2024 06:20:49.640 # Done loading RDB, keys loaded: 0, keys expired: 0.
2024-08-02_06:20:49.64054 77491:77491:M 02 Aug 2024 06:20:49.640 * DB loaded from disk: 0.000 seconds
2024-08-02_06:20:49.64078 77491:77558:M 02 Aug 2024 06:20:49.640 * Thread 0 alive.
```
 - Upgrade from 15.9.39 to 15.9.42 (redis to keydb): smooth upgrade but there are no whitelisted IP's persisted in the keydb even after using the same data directory.
 - Upgrade from 15.7.0 to 15.9.39 (redis to redis): there are no whitelisted IP's persisted in redis after upgrade.
 - It means that we are not persisting any whitelisted IP's in upgrade process as redis is just for caching purpose.
 - Conclusion: Keydb changes are working as expected in all the scenarios.

 - Regarding the 'old binary being removed from the package while it's still running on the system', In the upgrade process we first stop all the services before unpacking the CS package. So we stop the redis before keydb service up, Hence redis is no more running after upgrade. `chef-server-ctl stop;dpkg -i pkg;chef-server-ctl upgrade; chef-server-ctl start`

I hope, I have cleared the concerns over data/upgrade scenarios.

**Comment by jashaik** [comment]
https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6636

**Comment by jashaik** [comment]
Adhoc build afer rebase + Amazon 2 builder - https://buildkite.com/chef/chef-chef-server-main-omnibus-adhoc/builds/6678

**Pull request merged**
