### PR TITLE
level up travis build caching and use system gecode for faster builds

### PR DESCRIPTION
**Pull request by marcparadise**
* install sqitch to cache 
* install chef-dk 
* modify travis build to use chefk embedded libgecode instead of building with each run
* remove a couple of files that were causing our cache to get repackaged on every build 

ping @chef/lob

### CODE REVIEW

**Comment by stevendanna** [comment]
Heads up, I merged the "enable containers" portion of this here:

https://github.com/chef/chef-server/pull/282

I think the libgecode caching is probably the next biggest win in terms of test time.  Have we tried caching the entire bundle rather than building libgecode ourselves?

**Comment by marcparadise** [comment]
@stevendanna  I'm reluctant to cache components that are part of the build output - particularly if we want to look at building artifacts on travis at any point.

**Comment by stevendanna** [comment]
@mp I see, that makes sense.

**Comment by marcparadise** [comment]
Now updated with more accurate description.

**Comment by marcparadise** [comment]
Odd, github isn't picking up on the fact that this was merged.

**Pull request closed without merging**
