### PR TITLE
Make sure chef-server-ctl install can do chef-manage

### PR DESCRIPTION
**Pull request by jcreedcmu**
Should be ready to merge once new chef-manage is in the stable channel.

### CODE REVIEW

**Comment by stevendanna** [comment]
Have we pushed a chef-manage package to the stable repo yet?

**Comment by smith** [comment]
@stevendanna No not yet. This won't be able to merged until that happens, and that's probably the source of that error.

Is there a way to tell `chef-server-ctl install` to use the current channel?

**Comment by marcparadise** [comment]
There's not any way @smith

**Comment by marcparadise** [comment]
@smith @jcreedcmu any idea when chef-manage is making its way to stable? I thought I saw other changes suggesting that it had been done already, but I don't see it there.

**Comment by smith** [comment]
We're blocked waiting for ops to deploy 2.0.1 so we can link to the Hosted changelog. See (internal tickets) [VI-11](https://chefio.atlassian.net/browse/VI-11) and [OPS-162](https://chefio.atlassian.net/browse/OPS-162).

**Comment by marcparadise** [comment]
Thanks

**Comment by raskchanky** [comment]
chef-manage 2.1.1 and 2.1.0 are now both in the stable channel, and ops deployed 2.1.1 to hosted yesterday.

**Comment by stevendanna** [comment]
rebased this against master. :+1:

**Pull request merged**
