### PR TITLE
[scripts/import-components] Import chef-server components into this repo

### PR DESCRIPTION
**Pull request by stevendanna**
This script is a one-time-use script to import the components that
make up chef-server into this repository.  The final layout will look like:

```
.
|-- CONTRIBUTING.md
|-- LICENSE
|-- MAINTAINERS.md
|-- README.md
|-- oc-chef-pedant
|   |-- ...
|-- omnibus
|   |-- ...
`-- src
    |-- bookshelf
    |-- chef-mover
    |-- chef-server-bootstrap
    |-- oc-id
    |-- oc_bifrost
    |-- oc_erchef
    `-- opscode-expander
```

After this import, subsequent commits will be needed to the omnibus
build configuration to account for this layout.

### CODE REVIEW

**Comment by stevendanna** [comment]
cc @chef/lob @chef/chef-visual-interaction @danielsdeleo

**Comment by mmzyk** [comment]
Looks good to me, although I obviously haven't run the code to fully test it.

**Comment by danielsdeleo** [comment]
I haven't run the code but the repo layout LGTM

**Comment by tylercloke** [comment]
:clap: Looks good to me. Unify the repos!

**Pull request merged**
