### PR TITLE
Pin berkshelf-no-depselector to avoid pulling in 6.0

### PR DESCRIPTION
**Pull request by stevendanna**
Signed-off-by: Steven Danna <steve@chef.io>

### CODE REVIEW

**Comment by thommay** [comment]
wait why does chef-server have berkshelf in it?

**Comment by stevendanna** [comment]
@thommay It is a build-time dep to compile the cookbooks required for reconfigure.

**Comment by stevendanna** [comment]
Notably: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/Berksfile

**Comment by thommay** [comment]
Ah, i was concerned for a second there was some deep magic that relied on berkshelf. 👍

**Pull request merged**
